"""Groq provider — uses OpenAI-compatible API with Groq's endpoint."""
import os
import base64
import json
import re
from typing import List, Dict, Any, Optional
from openai import OpenAI

from utils.logger import get_logger

logger = get_logger("groq-service")

GROQ_BASE_URL = "https://api.groq.com/openai/v1"
DEFAULT_MODEL = "meta-llama/llama-4-scout-17b-16e-instruct"

SYSTEM_PROMPT = """You are an expert at extracting structured question data from scanned Indian FLN (Foundational Literacy & Numeracy) question papers for grades 1-8.

For each question visible on the page, output a JSON object with EXACTLY these fields:

{
  "questionNo": <integer>,
  "pageNumber": <integer>,
  "questionText": "<the exact question text, in the same language as the paper>",
  "questionType": "<one of: MCQ | True/False | Fill in the Blanks | Short Answer | Long Answer | Match the Following | Counting | Addition | Subtraction | Number Recognition | Drawing | Trace>",
  "concept": "<short concept label, e.g. 'Counting 1-10', 'Simple Addition', 'Reading Comprehension'>",
  "difficulty": "<Easy | Medium | Hard>",
  "marks": <integer 1-5>,
  "answerType": "<text | number | drawing | trace | multiple>",
  "correctAnswer": "<the correct answer — extracted from the paper if visible, otherwise COMPUTED/GENERATED by you based on the question>",
  "alternateAnswers": [<other accepted forms of the same answer>],
  "evaluationRule": "<exact | contains | tolerance | range | subjective | manual>",
  "boundingBox": { "x": <0>, "y": <0>, "width": <0>, "height": <0> }
}

**IMPORTANT — answer key generation rules:**
- Always fill `correctAnswer` even if the paper doesn't show one. For math/arithmetic questions, COMPUTE the answer.
- For example: '8 + 3 =' → correctAnswer = '11'; '15 - 6 =' → correctAnswer = '9'; 'What comes after Tuesday?' → correctAnswer = 'Wednesday'.
- For MCQs, the correctAnswer should be the option letter OR the option text.
- If the question has no objectively correct answer (Drawing, Trace, subjective Long Answer), set correctAnswer = '' and evaluationRule = 'manual'.
- List 2-3 acceptable alternate spellings/forms in alternateAnswers when reasonable.

Return a JSON array of these objects (no prose, no markdown fences):
[
  { ... },
  { ... }
]
"""


def _strip_code_fence(text: str) -> str:
    text = text.strip()
    text = re.sub(r"^```(?:json)?", "", text).strip()
    text = re.sub(r"```$", "", text).strip()
    return text


def _extract_json(text: str) -> Optional[Any]:
    text = _strip_code_fence(text)
    try:
        return json.loads(text)
    except Exception:
        m = re.search(r"\[[\s\S]*\]", text)
        if m:
            try:
                return json.loads(m.group(0))
            except Exception:
                pass
    return None


_client: Optional[OpenAI] = None


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY not set")
        _client = OpenAI(api_key=api_key, base_url=GROQ_BASE_URL)
    return _client


def is_configured() -> bool:
    return bool(os.environ.get("GROQ_API_KEY"))


def get_model() -> str:
    return os.environ.get("GROQ_MODEL", DEFAULT_MODEL)


def analyze_page(image_bytes: bytes, page_number: int, metadata: Dict[str, Any] = None) -> List[Dict[str, Any]]:
    metadata = metadata or {}
    if not is_configured():
        logger.warning("GROQ_API_KEY not set")
        return []

    b64 = base64.b64encode(image_bytes).decode("ascii")
    model = get_model()

    user_text = (
        f"\nContext: Title='{metadata.get('title','')}', "
        f"Subject='{metadata.get('subject','')}', Grade='{metadata.get('grade','')}', "
        f"Language='{metadata.get('language','English')}', Page={page_number}"
    )

    try:
        client = _get_client()
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": user_text},
                        {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{b64}"}},
                    ],
                },
            ],
            temperature=0.2,
            max_tokens=4096,
        )
        text = response.choices[0].message.content or ""
        data = _extract_json(text)
        if not isinstance(data, list):
            logger.warning(f"Groq returned non-list JSON for page {page_number}")
            return []
        for q in data:
            q.setdefault("pageNumber", page_number)
        return data
    except Exception as e:
        logger.exception(f"Groq error on page {page_number}: {e}")
        return []